currency: " coins"
currency-before-number: false               # i.e.: $5 instead of 5$
tax: 0.01                                   # 1% tax
auction-duration: 172800                    # the time an auction lasts in seconds
auction-setup-time: 30                      # the time it takes to put an item on auction
filler-item: "BLACK_STAINED_GLASS_PANE"
format-numbers: "#,###.##"                  # this is used to format numbers. Here you can learn how to do it: https://www.gooddata.com/docs/cloud/create-metrics/format-numbers/
format-time-characters: "dhms"              # these characters are used to format time, e.g. 1d 2h 3m 4s
default-max-auctions: 10
sold-message: true                          # send a message to the player when one of their auctions is sold
auto-collect: false                         # automatically gives the money to the player when an auction is bought and removes it from the ah
partial-selling: false                      # allows players to select the amount of items they want to buy of an auction
admin-permission: "auctionhouse.moderator"
display-update: 20                          # 20 ticks = 1 second, how frequently the item displays are updated; can be set to 1 for instant updates